import "../../globals.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="bg-gray-50">
      {children}
    </div>
  );
}
